# Generated by Django 5.0.3 on 2024-03-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microgrid_back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='site/logo/')),
            ],
            options={
                'verbose_name': 'site',
                'verbose_name_plural': '1. Site',
            },
        ),
    ]
