# Generated by Django 5.0.3 on 2024-04-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microgrid_back', '0002_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.AlterModelTable(
            name='measurements',
            table='measurements',
        ),
    ]
