# Generated by Django 4.2.11 on 2024-04-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microgrid_back', '0002_measurementsfive_rmsvalue_measurementsfour_rmsvalue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurementsfive',
            old_name='voltage',
            new_name='sensdata',
        ),
        migrations.RenameField(
            model_name='measurementsfour',
            old_name='voltage',
            new_name='sensdata',
        ),
        migrations.RenameField(
            model_name='measurementsone',
            old_name='voltage',
            new_name='sensdata',
        ),
        migrations.RenameField(
            model_name='measurementssix',
            old_name='voltage',
            new_name='sensdata',
        ),
        migrations.RenameField(
            model_name='measurementsthree',
            old_name='voltage',
            new_name='sensdata',
        ),
        migrations.RenameField(
            model_name='measurementstwo',
            old_name='voltage',
            new_name='sensdata',
        ),
        migrations.AddField(
            model_name='measurementsfive',
            name='pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Power Factor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementsfive',
            name='sname',
            field=models.CharField(default='Voltage', max_length=50, verbose_name='Sensor Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementsfive',
            name='stype',
            field=models.CharField(choices=[('Current', 'Current'), ('Voltage', 'Voltage')], default='Current', max_length=50, verbose_name='Sensor Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementsfive',
            name='thd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Harmonic Distortion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementsfour',
            name='pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Power Factor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementsfour',
            name='sname',
            field=models.CharField(default='Voltage', max_length=50, verbose_name='Sensor Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementsfour',
            name='stype',
            field=models.CharField(choices=[('Current', 'Current'), ('Voltage', 'Voltage')], default='Voltage', max_length=50, verbose_name='Sensor Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementsfour',
            name='thd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Harmonic Distortion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementsone',
            name='pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Power Factor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementsone',
            name='sname',
            field=models.CharField(default='Voltage', max_length=50, verbose_name='Sensor Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementsone',
            name='stype',
            field=models.CharField(choices=[('Current', 'Current'), ('Voltage', 'Voltage')], default='Voltage', max_length=50, verbose_name='Sensor Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementsone',
            name='thd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Harmonic Distortion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementssix',
            name='pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Power Factor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementssix',
            name='sname',
            field=models.CharField(default='Voltage', max_length=50, verbose_name='Sensor Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementssix',
            name='stype',
            field=models.CharField(choices=[('Current', 'Current'), ('Voltage', 'Voltage')], default='Voltage', max_length=50, verbose_name='Sensor Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementssix',
            name='thd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Harmonic Distortion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementsthree',
            name='pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Power Factor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementsthree',
            name='sname',
            field=models.CharField(default='Voltage', max_length=50, verbose_name='Sensor Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementsthree',
            name='stype',
            field=models.CharField(choices=[('Current', 'Current'), ('Voltage', 'Voltage')], default='Voltage', max_length=50, verbose_name='Sensor Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementsthree',
            name='thd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Harmonic Distortion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementstwo',
            name='pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Power Factor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementstwo',
            name='sname',
            field=models.CharField(default='Voltage', max_length=50, verbose_name='Sensor Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementstwo',
            name='stype',
            field=models.CharField(choices=[('Current', 'Current'), ('Voltage', 'Voltage')], default='Voltage', max_length=50, verbose_name='Sensor Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementstwo',
            name='thd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Harmonic Distortion'),
            preserve_default=False,
        ),
    ]
